---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-app
  labels:
    app: mc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mc-app
  template:
    metadata:
      labels:
        app: mc-app
    spec:
      containers:
      - name: mc-app
        image: vamsi01/java-web:40
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: mc-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: mc-app
